"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type SaveState = { kind: "idle" } | { kind: "saving" } | { kind: "error"; message: string };

/**
 * Step 2 of connecting Steam (ADR-0012). Sign-in only proved identity; Steam
 * has no scoped-token flow for the Web API, so the key still has to be
 * generated by hand on Steam's own site and pasted here — this form exists
 * to make that the *only* manual step, instead of also hunting down a
 * SteamID64 and hand-editing `.env.local`.
 */
export function ApiKeyForm({ steamId }: { steamId: string }) {
  const router = useRouter();
  const [apiKey, setApiKey] = useState("");
  const [state, setState] = useState<SaveState>({ kind: "idle" });

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!apiKey.trim()) return;

    setState({ kind: "saving" });
    try {
      const res = await fetch("/api/steam-connection", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ steamId, apiKey }),
      });
      const body = await res.json();

      if (!res.ok) {
        setState({ kind: "error", message: body.error ?? `HTTP ${res.status}` });
        return;
      }

      router.push("/library");
      router.refresh();
    } catch (err) {
      setState({
        kind: "error",
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return (
    <div className="rounded-xl border border-white/12 bg-white/[0.03] p-6 text-sm leading-relaxed text-[#a8a69f]">
      <p className="mb-1">
        Signed in as <span className="text-[#e9e7e0]">SteamID {steamId}</span>.
      </p>
      <p className="mb-4">
        Last step — Steam has no way to hand out a scoped access token, so
        grab a Web API key by hand:
      </p>
      <a
        href="https://steamcommunity.com/dev/apikey"
        target="_blank"
        rel="noreferrer"
        className="mb-4 inline-block text-[#7fb6df] hover:underline"
      >
        steamcommunity.com/dev/apikey →
      </a>

      <form onSubmit={submit} className="mt-4">
        <label className="mb-1 block text-xs text-[#8e8d86]">API key</label>
        <input
          autoFocus
          value={apiKey}
          onChange={(e) => setApiKey(e.target.value)}
          placeholder="paste it here"
          className="mb-3 w-full rounded-md border border-white/15 bg-black/30 px-2 py-1.5 text-xs text-[#e9e7e0] outline-none placeholder:text-[#4e4d49] focus:border-white/35"
        />

        {state.kind === "error" && (
          <p className="mb-3 text-xs text-[#e8877b]">{state.message}</p>
        )}

        <button
          type="submit"
          disabled={state.kind === "saving" || !apiKey.trim()}
          className="rounded-lg border border-white/25 px-4 py-2 text-[13px] text-[#e9e7e0] transition hover:border-white/45 hover:bg-white/5 disabled:opacity-40"
        >
          {state.kind === "saving" ? "connecting…" : "connect"}
        </button>
      </form>
    </div>
  );
}
