"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type SaveState = { kind: "idle" } | { kind: "saving" } | { kind: "error"; message: string };

/**
 * Step 2 of connecting Steam (ADR-0012). Sign-in only proved identity; Steam
 * has no scoped-token flow for the Web API, so the key still has to be
 * generated by hand on Steam's own site and pasted here — this form exists
 * to make that the *only* manual step, instead of also hunting down a
 * SteamID64 and hand-editing `.env.local`.
 */
export function ApiKeyForm({ steamId }: { steamId: string }) {
  const router = useRouter();
  const [apiKey, setApiKey] = useState("");
  const [state, setState] = useState<SaveState>({ kind: "idle" });

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!apiKey.trim()) return;

    setState({ kind: "saving" });
    try {
      const res = await fetch("/api/steam-connection", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ steamId, apiKey }),
      });
      const body = await res.json();

      if (!res.ok) {
        setState({ kind: "error", message: body.error ?? `HTTP ${res.status}` });
        return;
      }

      router.push("/library");
      router.refresh();
    } catch (err) {
      setState({
        kind: "error",
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return (
    <div className="panel p-8">
      <p className="drawer-label mb-5">file a key</p>

      <p className="text-sm leading-relaxed text-paper-dim">
        Steam has no way to hand out a scoped access token, so a Web API key
        has to be generated by hand and pasted here.
      </p>

      <a
        href="https://steamcommunity.com/dev/apikey"
        target="_blank"
        rel="noreferrer"
        className="catalog mt-5 inline-block text-amber underline decoration-[var(--amber-deep)] underline-offset-4 hover:decoration-[var(--amber)]"
      >
        steamcommunity.com/dev/apikey →
      </a>

      <form onSubmit={submit} className="mt-8">
        <label className="field-label">api key · for steamid {steamId}</label>
        <input
          autoFocus
          value={apiKey}
          onChange={(e) => setApiKey(e.target.value)}
          placeholder="paste it here"
          className="field font-mono text-xs"
        />

        {state.kind === "error" && (
          <p className="catalog mt-4 leading-[1.9] text-rust">{state.message}</p>
        )}

        <button
          type="submit"
          disabled={state.kind === "saving" || !apiKey.trim()}
          className="btn btn-primary mt-7"
        >
          {state.kind === "saving" ? "connecting…" : "connect"}
        </button>
      </form>
    </div>
  );
}
